### ISSUE TITLE
Update button errors with contract violaton

### ISSUE THREAD

**Issue by marksherman** [oplS15projects/GrEP#17]
```
#<procedure:n-func>. . function: contract violation
  expected: (or/c exact-integer? (or/c (list/c real? real? real?) string? symbol? (is-a?/c color%)))
  given: #<eof>
```

Violation is on line 54. It's getting eof instead of data, so this simply doesn't work for me.

Please advise.

**Comment by mike01720** [comment]
We figured out that we didn't set default values for the colors so you need to make sure there is a number in the color text box when you are using a function.

**Comment by marksherman** [comment]
That's it! Please update to provide a default or a case to handle empty value

**Comment by nick01720** [comment]
Updated gui.rkt to have default color values, and added some default function values.

**Comment by marksherman** [comment]
That looks great. Thank you. All set.
